import 'dart:io';
import 'dart:typed_data';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:thaitalk/services/app_settings.dart';
import 'package:thaitalk/services/speech_cache.dart';
import 'package:thaitalk/services/speech_service.dart';
import 'package:thaitalk/services/speech_settings.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  setUp(() => SharedPreferences.setMockInitialValues({}));
  test(
    'pre-existing version 1 WAV filename is reused without Azure credentials',
    () async {
      final directory = await Directory.systemTemp.createTemp(
        'thaitalk-tts-v1-',
      );
      addTearDown(() => directory.delete(recursive: true));
      final wav = pcmToWav(Uint8List(3200));
      // Fixed digest generated by the original Android app for this utterance.
      await File(
        '${directory.path}/15c6eb0441028d2e25fadc161f47f1156745345144181ec468a135634a5a3aad.wav',
      ).writeAsBytes(wav);
      final speech = SpeechService(
        preferences: AppSettings(),
        settings: SpeechSettings(),
        diskCache: SpeechCache(directory: directory),
        client: MockClient(
          (_) async => throw StateError('Cache hit must not request Azure'),
        ),
      );
      addTearDown(speech.dispose);
      expect(await speech.loadSpeechAudio('สวัสดีครับ'), wav);
    },
  );

  test(
    'Direct Azure WAV persists across restarts and works offline without configuration',
    () async {
      final directory = await Directory.systemTemp.createTemp(
        'thaitalk-tts-test-',
      );
      addTearDown(() => directory.delete(recursive: true));
      final pcm = Uint8List(3200);
      final wav = pcmToWav(pcm);
      var requests = 0;
      final requestedVoices = <String>[];
      final first = SpeechService(
        preferences: AppSettings(),
        settings: SpeechSettings(apiKey: 'test-key', region: 'southeastasia'),
        diskCache: SpeechCache(directory: directory),
        client: MockClient((request) async {
          requests++;
          expect(request.url.host, 'southeastasia.tts.speech.microsoft.com');
          requestedVoices.add(
            RegExp('voice name="([^"]+)"').firstMatch(request.body)!.group(1)!,
          );
          return http.Response.bytes(
            pcm,
            200,
            headers: {'content-type': 'audio/basic'},
          );
        }),
      );
      expect(await first.loadSpeechAudio('สวัสดีครับ'), wav);
      expect(await first.loadSpeechAudio('สวัสดีครับ'), wav);
      expect(requests, 1);
      await first.loadSpeechAudio('สวัสดีครับ', slow: true);
      await first.loadSpeechAudio('สวัสดีครับ', male: false);
      expect(requests, 3);
      expect(requestedVoices, [
        'th-TH-NiwatNeural',
        'th-TH-NiwatNeural',
        'th-TH-PremwadeeNeural',
      ]);
      first.dispose();
      final reopened = SpeechService(
        preferences: AppSettings(),
        settings: SpeechSettings(),
        diskCache: SpeechCache(directory: directory),
        client: MockClient((_) async {
          requests++;
          throw const SocketException('offline');
        }),
      );
      expect(await reopened.loadSpeechAudio('สวัสดีครับ'), wav);
      expect(await reopened.loadSpeechAudio('สวัสดีครับ', slow: true), wav);
      expect(await reopened.loadSpeechAudio('สวัสดีครับ', male: false), wav);
      expect(requests, 3);
      await expectLater(
        reopened.loadSpeechAudio('ขอบคุณครับ'),
        throwsA(
          isA<SpeechException>().having(
            (error) => error.message,
            'setup guidance',
            contains('APK'),
          ),
        ),
      );
      expect(requests, 3);
      reopened.dispose();
    },
  );
}
